package com.fc.test.mapper.workorder;

import com.fc.test.model.workorder.AlarmWorkOrderEntity;
import com.fc.test.model.workorder.AlarmWorkOrderEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlarmWorkOrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    long countByExample(AlarmWorkOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int deleteByExample(AlarmWorkOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int insert(AlarmWorkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int insertSelective(AlarmWorkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    List<AlarmWorkOrderEntity> selectByExample(AlarmWorkOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    AlarmWorkOrderEntity selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AlarmWorkOrderEntity record, @Param("example") AlarmWorkOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AlarmWorkOrderEntity record, @Param("example") AlarmWorkOrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AlarmWorkOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmwork_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AlarmWorkOrderEntity record);
}