package com.fc.test.mapper.workorder;

import com.fc.test.model.workorder.NotificationLogEntity;
import com.fc.test.model.workorder.NotificationLogEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotificationLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    long countByExample(NotificationLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int deleteByExample(NotificationLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long notificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int insert(NotificationLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int insertSelective(NotificationLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    List<NotificationLogEntity> selectByExample(NotificationLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    NotificationLogEntity selectByPrimaryKey(Long notificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NotificationLogEntity record, @Param("example") NotificationLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NotificationLogEntity record, @Param("example") NotificationLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotificationLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotificationLogEntity record);
}