package com.fc.test.model.workorder;

import lombok.ToString;

import java.util.Date;

@ToString
public class AlarmWorkOrderEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.working_state
     *
     * @mbg.generated
     */
    private Byte workingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.order_create_time
     *
     * @mbg.generated
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmwork_order.order_finish_time
     *
     * @mbg.generated
     */
    private Date orderFinishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.order_id
     *
     * @return the value of alarmwork_order.order_id
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.order_id
     *
     * @param orderId the value for alarmwork_order.order_id
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.group_id
     *
     * @return the value of alarmwork_order.group_id
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.group_id
     *
     * @param groupId the value for alarmwork_order.group_id
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.device_id
     *
     * @return the value of alarmwork_order.device_id
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.device_id
     *
     * @param deviceId the value for alarmwork_order.device_id
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.working_state
     *
     * @return the value of alarmwork_order.working_state
     * @mbg.generated
     */
    public Byte getWorkingState() {
        return workingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.working_state
     *
     * @param workingState the value for alarmwork_order.working_state
     * @mbg.generated
     */
    public void setWorkingState(Byte workingState) {
        this.workingState = workingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.order_create_time
     *
     * @return the value of alarmwork_order.order_create_time
     * @mbg.generated
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.order_create_time
     *
     * @param orderCreateTime the value for alarmwork_order.order_create_time
     * @mbg.generated
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmwork_order.order_finish_time
     *
     * @return the value of alarmwork_order.order_finish_time
     * @mbg.generated
     */
    public Date getOrderFinishTime() {
        return orderFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmwork_order.order_finish_time
     *
     * @param orderFinishTime the value for alarmwork_order.order_finish_time
     * @mbg.generated
     */
    public void setOrderFinishTime(Date orderFinishTime) {
        this.orderFinishTime = orderFinishTime;
    }
}